### ISSUE TITLE
Release APP

### ISSUE THREAD

**Issue by liujinlong123** [Grigory-Rylov/android-layout-inspector#18]
Can the release application be used

**Comment by liujinlong123** [comment]
?

**Comment by Grigory-Rylov** [comment]
Hello, you can use it with release app only on rooted device.

**Comment by liujinlong123** [comment]
Thank you, I'll try. I've tried official tools before - Layout Inspector, It doesn't work.

**Comment by liujinlong123** [comment]
Thank you, It works.
