### ISSUE TITLE
Android Stuido Giraffe Not work

### ISSUE THREAD

**Issue by zjw-swun** [Grigory-Rylov/android-layout-inspector#32]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/11499027/233541432-9541a636-c52e-4989-8f80-d3b7a83d3f23.png">

**Comment by Grigory-Rylov** [comment]
Thanks for report! I'll try to fix it

**Comment by Grigory-Rylov** [comment]
Please, try this version https://github.com/Grigory-Rylov/android-layout-inspector/releases/download/v23.05.11.0/android-layout-inspector-plugin-23.05.11.0.zip 
If it works, then I will send it to the JetBrains store.

**Comment by CXStudioTeam** [comment]
It still can not work on Giraffe. @Grigory-Rylov 
![yali](https://github.com/Grigory-Rylov/android-layout-inspector/assets/51486193/354bfdf6-bb30-4011-a1a3-bd8a4c0bd4e4)
