### ISSUE TITLE
The 23.05.11 version still can not work on Giraffe.

### ISSUE THREAD

**Issue by CXStudioTeam** [Grigory-Rylov/android-layout-inspector#35]
![yali](https://github.com/Grigory-Rylov/android-layout-inspector/assets/51486193/60fe42b5-72e6-4ea1-8706-f22cd0df3ba7)

**Comment by Grigory-Rylov** [comment]
Please try 23.08.18.0
https://github.com/Grigory-Rylov/android-layout-inspector/releases/download/v23.08.18.0/android-layout-inspector-plugin-23.08.18.0.zip
