### ISSUE TITLE
Work with Intellij Beta

### ISSUE THREAD

**Issue by NoelJacob** [Grigory-Rylov/android-layout-inspector#42]
![image](https://github.com/Grigory-Rylov/android-layout-inspector/assets/54862022/4aac8507-ee88-49c5-b848-8f58197119e4)

**Comment by renyuzhuo** [comment]
@NoelJacob 
I made a package for temporary use only until the repository owner upgrades.

https://github.com/renyuzhuo/android-layout-inspector/blob/master/android-layout-inspector-plugin-23.10.03.2.zip

**Comment by Grigory-Rylov** [comment]
Sorry, I forgot to update version with fix, there is https://github.com/Grigory-Rylov/android-layout-inspector/releases/download/v24.03.06.0/android-layout-inspector-plugin-24.03.06.0.zip

I sent it to the store for moderation.

**Comment by Grigory-Rylov** [comment]
Hello, new version just published https://plugins.jetbrains.com/plugin/15227-yali/versions/stable/500161

**Comment by NoelJacob** [comment]
Now it shows needs android studio for running it. I already installed it from the link above. Why not run on intellij IDEA too?

**Comment by Grigory-Rylov** [comment]
Unfortunately  YALI  used android studio's libraries that is why should be runnin  in Android Studio.

**Comment by NoelJacob** [comment]
Doesn't the Android plugin of IDEA provide the same Android studio functionality in IDEA ?
